name: "Validate and Deploy Infrastructure"

on:
  push:
    branches:
      - main
      - tf-w1-network
      - tf-chore1-cicd
  pull_request:

jobs:
  terraform:
    name: "Configure Terraform"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Terraform cli
        run: |
          sudo curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add - && sleep 5
          sudo apt-add-repository "deb [arch=$(dpkg --print-architecture)] https://apt.releases.hashicorp.com $(lsb_release -cs) main" && sleep 10
          sudo apt install terraform 
          terraform version
   
   
      - name: Navigate to networking directory
        if: github.ref == 'refs/heads/tf-chore1-cicd'
        run: |
           ls -al && cd terraform/net

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform init
      
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
